[package]
name = "xsd_onvif"
version = "0.1.0"
authors = ["leonid.krutovsky <leonid.krutovsky@invitae.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.10.1"
xsd10 = {path = "../../CXT/xsd10"}