[package]
name = "ez-wsdl"
version = "0.1.0"
authors = ["Chris Bruce <chris@lumeo.com>", "leonid.krutovsky <leonid.krutovsky@quantumsoft.ru>", "DmitrySamoylov <dmitry.samoylov@quantumsoft.ru>", "victor-soloviev <victor.soloviev@quantumsoft.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ez_wsdl"
path = "src/lib.rs"

[dependencies]
roxmltree = "0.10.1"
Inflector = "*"
clap = "2.33.0"

[dev-dependencies]
syn = { version = "1.0", features = ["full"] }
log = "0.4.8"
xml-rs = "0.8.0"
text-diff = "0.4.0"
num-bigint = "0.2.6"
bigdecimal = "0.1.0"


