pub mod abstract_;
pub mod attribute_form_default;
pub mod block;
// pub mod block_default;
// pub mod default;
// pub mod element_form_default;
// pub mod final_;
// pub mod final_default;
// pub mod fixed;
// pub mod form;
// pub mod id;
// pub mod max_occurs;
// pub mod min_occurs;
// pub mod mixed;
// pub mod name;
// pub mod namespace;
// pub mod nillable;
// pub mod process_contents;
// pub mod public;
// pub mod ref_;
// pub mod refer;
// pub mod schema_location;
// pub mod source;
// pub mod substitution_group;
// pub mod system;
// pub mod target_namespace;
// pub mod type_;
// pub mod use_;
// pub mod version;
// pub mod xpath;
